question_data = [
    {"text": "Python was created by Guido van Rossum.", "answer": "True"},
    {"text": "Python supports multiple inheritance.", "answer": "True"},
    {"text": "In Python, lists are immutable.", "answer": "False"},
    {"text": "The 'lambda' keyword is used to create anonymous functions in Python.", "answer": "True"},
    {"text": "The '==' operator checks if two variables point to the same object.", "answer": "False"},
    {"text": "Python uses curly braces {} to define blocks of code.", "answer": "False"},
    {"text": "Python is a statically typed language.", "answer": "False"},
    {"text": "You can use list comprehensions in Python to create new lists.", "answer": "True"},
    {"text": "The 'with' statement in Python is used for exception handling.", "answer": "False"},
    {"text": "Dictionaries in Python are unordered collections of key-value pairs (prior to Python 3.7).", "answer": "True"},
    {"text": "The Python interpreter ignores comments in the code.", "answer": "True"},
    {"text": "The Zen of Python can be accessed by typing 'import this' in the interpreter.", "answer": "True"},
    {"text": "Python's 'pass' statement is used to exit a loop prematurely.", "answer": "False"},
    {"text": "In Python, 'None' is equivalent to 0.", "answer": "False"},
    {"text": "The 'is' operator checks for value equality in Python.", "answer": "False"},
    {"text": "Python's 'range' function includes the end value.", "answer": "False"},
    {"text": "You can define a function inside another function in Python.", "answer": "True"},
    {"text": "Python's 'set' data structure allows duplicate elements.", "answer": "False"},
    {"text": "The 'global' keyword in Python allows you to modify a global variable inside a function.", "answer": "True"},
    {"text": "Python's 'try' block must be followed by an 'except' block.", "answer": "True"},
    {"text": "In Python, 'elif' is short for 'else if'.", "answer": "True"},
    {"text": "Python's 'open' function is used to open files.", "answer": "True"},
    {"text": "The 'append' method adds an element to the end of a list.", "answer": "True"},
    {"text": "Python lists can contain elements of different data types.", "answer": "True"},
    {"text": "The 'break' statement exits the current loop.", "answer": "True"},
    {"text": "Python's 'continue' statement stops the entire program.", "answer": "False"},
    {"text": "In Python, strings are mutable.", "answer": "False"},
    {"text": "The 'len' function returns the length of an object.", "answer": "True"},
    {"text": "Python's 'int' function can convert a string to an integer.", "answer": "True"},
    {"text": "The 'float' function in Python converts a number to a floating-point number.", "answer": "True"},
    {"text": "Python's 'bool' function returns True for all values except 0 and empty collections.", "answer": "False"},
    {"text": "The 'type' function returns the data type of an object.", "answer": "True"},
    {"text": "Python's 'input' function reads a line from input and returns it as a string.", "answer": "True"},
    {"text": "The 'print' function in Python writes text to the console.", "answer": "True"},
    {"text": "Python's 'int' function can convert a floating-point number to an integer by truncating the decimal part.", "answer": "True"},
    {"text": "The 'str' function converts an object to its string representation.", "answer": "True"},
    {"text": "Python's 'list' function can convert a string into a list of characters.", "answer": "True"},
    {"text": "The 'dict' function creates a new dictionary.", "answer": "True"},
    {"text": "Python's 'tuple' function can convert a list into a tuple.", "answer": "True"},
    {"text": "The 'set' function removes duplicate elements from a list.", "answer": "True"},
    {"text": "Python's 'max' function returns the smallest item in an iterable.", "answer": "False"},
    {"text": "The 'min' function returns the largest item in an iterable.", "answer": "False"},
    {"text": "Python's 'sum' function adds all the items in an iterable.", "answer": "True"},
    {"text": "The 'sorted' function returns a new sorted list from the elements of any iterable.", "answer": "True"},
    {"text": "Python's 'reversed' function returns a reversed iterator.", "answer": "True"},
    {"text": "The 'enumerate' function adds a counter to an iterable.", "answer": "True"},
    {"text": "Python's 'zip' function combines two or more iterables into a single iterable of tuples.", "answer": "True"},
    {"text": "The 'map' function applies a function to all the items in an input list.", "answer": "True"},
    {"text": "Python's 'filter' function filters the elements of an iterable based on a function.", "answer": "True"},
    {"text": "The 'reduce' function is a built-in function in Python 3.", "answer": "False"},
    {"text": "Python's 'any' function returns True if all elements of the iterable are true.", "answer": "False"},
    {"text": "The 'all' function returns True if any element of the iterable is true.", "answer": "False"},
    {"text": "Python's 'chr' function returns the string representing a character whose Unicode code point is the integer passed.", "answer": "True"},
    {"text": "The 'ord' function returns the Unicode code point for a given character.", "answer": "True"},
    {"text": "Python's 'bin' function converts an integer to a binary string.", "answer": "True"},
    {"text": "The 'hex' function converts an integer to a hexadecimal string.", "answer": "True"},
    {"text": "Python's 'oct' function converts an integer to an octal string.", "answer": "True"},
    {"text": "The 'abs' function returns the absolute value of a number.", "answer": "True"},
    {"text": "Python's 'round' function rounds a number to a given precision in decimal digits.", "answer": "True"},
    {"text": "The 'pow' function returns the value of x to the power of y.", "answer": "True"},
    {"text": "Python's 'divmod' function returns the quotient and remainder of dividing two numbers.", "answer": "True"},
    {"text": "The 'isinstance' function checks if an object is an instance of a class or a tuple of classes.", "answer": "True"},
    {"text": "Python's 'issubclass' function checks if a class is a subclass of another class or a tuple of classes.", "answer": "True"},
    {"text": "The 'id' function returns the identity of an object.", "answer": "True"},
    {"text": "Python's 'hash' function returns the hash value of an object.", "answer": "True"},
    {"text": "The 'help' function invokes the built-in help system.", "answer": "True"},
    {"text": "Python's 'dir' function attempts to return a list of valid attributes of the object.", "answer": "True"},
    {"text": "The 'eval' function parses the expression passed to it and executes Python expressions within the program.", "answer": "True"},
    {"text": "Python's 'exec' function supports dynamic execution of Python code.", "answer": "True"},
    {"text": "The 'compile' function compiles the source into a code or AST object.", "answer": "True"},
    {"text": "Python's 'globals' function returns a dictionary representing the current global symbol table.", "answer": "True"},
    {"text": "The 'locals' function updates and returns a dictionary representing the current local symbol table.", "answer": "True"},
    {"text": "Python's 'callable' function checks if the object appears callable.", "answer": "True"},
    {"text": "The 'format' function formats a specified value.", "answer": "True"},
    {"text": "Python's 'memoryview' function returns a memory view object.", "answer": "True"},
    {"text": "The 'object' function returns a new featureless object.", "answer": "True"},
    {"text": "Python's 'super' function returns a proxy object that delegates method calls to a parent or sibling class.", "answer": "True"},
    {"text": "The 'vars' function returns the __dict__ attribute for a module, class, instance, or any other object with a __dict__ attribute.", "answer": "True"},
    {"text": "Python's 'staticmethod' function transforms a method into a static method.", "answer": "True"},
    {"text": "The 'classmethod' function transforms a method into a class method.", "answer": "True"},
    {"text": "Python's 'property' function returns a property attribute.", "answer": "True"},
    {"text": "The 'delattr' function deletes the named attribute from the given object.", "answer": "True"},
    {"text": "Python's 'getattr' function returns the value of the named attribute of an object.", "answer": "True"},
    {"text": "The 'hasattr' function returns True if the object has the named attribute.", "answer": "True"},
    {"text": "Python's 'setattr' function sets the value of the named attribute of an object.", "answer": "True"},
    {"text": "The 'frozenset' function returns a new frozenset object, optionally with elements taken from iterable.", "answer": "True"},
    {"text": "Python's 'bytearray' function returns a new array of bytes.", "answer": "True"},
    {"text": "The 'bytes' function returns a new 'bytes' object.", "answer": "True"},
    {"text": "Python's 'complex' function creates a complex number.", "answer": "True"}
]